# Cloudflare Workers 配置文件

name = "ic123-backend"
main = "backend/dist/index.js"
compatibility_date = "2024-03-18"
node_compat = true

# 环境变量
[env.production.vars]
NODE_ENV = "production"
PORT = "8787"
API_PREFIX = "/api"
CORS_ORIGIN = "https://ic123.pages.dev"

# Supabase配置（需要在Cloudflare Dashboard中设置）
# SUPABASE_URL = "https://your-project-id.supabase.co"
# SUPABASE_ANON_KEY = "your-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

# 开发环境
[env.development.vars]
NODE_ENV = "development"
PORT = "8787"
API_PREFIX = "/api"
CORS_ORIGIN = "http://localhost:3000"