# Cloudflare Workers 后端API配置

name = "ic123-backend"
main = "src/index.ts"
compatibility_date = "2024-03-18"

# 生产环境
[env.production]
name = "ic123-backend"

[env.production.vars]
NODE_ENV = "production"
# Supabase配置需要在Cloudflare Workers中设置为secrets
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-supabase-service-role-key"

# 开发环境
[env.development]
name = "ic123-backend-dev"

[env.development.vars]
NODE_ENV = "development"
# 开发环境的Supabase配置也需要设置为secrets

# 部署配置
[build]
command = "npm run build"
watch_dir = "src"

# KV存储（如需要缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"